name: pincode_input_fields
description: "Pincode input fields flutter package."
version: 1.0.0
homepage: https://github.com/PationPrime/pincode_input_fields

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
  web:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true